### ISSUE TITLE
论文配图不是很直观

### ISSUE THREAD

**Issue by JasonLeeFdu** [qhfan/RALA#1]
另外，figure1的维度是不是搞错了？

**Comment by JasonLeeFdu** [comment]
动机这块图还可以。主要是Fig6的计算方式这里，有点跟不上
个人感觉要加一个Qg到的红色小方块的箭头 不然看不出为啥求Qg。而且好像还掉了一个concat操作，把Yi给cat成Y，不然小方块怎么变成长条的。圈叉不知道是不是这个意思。
Fig6这一部分最好丰富一下caption，知道你上面的图是在做什么。
我真的是...免费peer review，上班之前闲的，哈哈哈

**Comment by JasonLeeFdu** [comment]
感觉应该是不错的文章 希望早日收进我的zotero里

**Comment by qhfan** [comment]
哈哈哈，感谢你的意见，我们还在修改

**Comment by qhfan** [comment]
确实，这块不太好画，怎么画都好丑
