### ISSUE TITLE
Lose the denominator in the final equation?

### ISSUE THREAD

**Issue by Journey7331** [qhfan/RALA#3]
Hi, great work!
As you say, linear attention can be formed like:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/f6a25811-50e3-4809-93ba-d0a6123affe0">

But did you forget the denominator in the final equation(6)?
<img width="398" alt="image" src="https://github.com/user-attachments/assets/c52752c0-382f-476a-89cc-abd3a4b0f34b">

Or maybe I missed any paragraphs?

**Comment by Journey7331** [comment]
And the concepts of `kv_aug` and `output_aug` seem somewhat similar to `Competition and Allocation mechanisms` that introduced in Flowformer? [ [pdf](https://arxiv.org/pdf/2202.06258.pdf) ] [ [github](https://github.com/thuml/Flowformer) ]

No offense, but just curious

**Comment by qhfan** [comment]
Thank you for your interest in our work. At the beginning of the method section, we mention that the rank of the matrix depends solely on the numerator and is independent of the denominator. Therefore, for the sake of simplicity, we subsequently focus our discussion exclusively on the numerator.
<img width="331" alt="image" src="https://github.com/user-attachments/assets/8027538d-853f-47e5-a88c-6ad7309e6d7f">

**Comment by qhfan** [comment]
After carefully reading FlowFormer, I believe that our method does not share many similarities with FlowFormer. The `kv_aug` involves the rearrangement of each token in the KV buffer, with the sole purpose of altering the useful information content in the KV buffer to increase the matrix rank, as detailed in the appendix. Compared to the design of Competition, the computation of `kv_aug` is simpler. On the other hand, the true effect of `out_aug` lies in the use of the Hadamard product operator, where the choice of $\phi$ does not require meticulous design. As demonstrated in our ablation experiments and the analysis in the appendix, even a simple identity mapping can achieve similar effects.

Furthermore, thank you for your suggestion; we will add comparative experiments with FlowFormer.

**Comment by Journey7331** [comment]
- Yes, the numerator is the important part.
So, in code implementation, the denominator part still exists?

- Got it, thanks for your patient explanation. :)

- Also curious about that why here you use `Q` with `k(K)` to get the `global_attn` or `alpha`, but not `k(Q)` and `k(K)`?
<img width="397" alt="image" src="https://github.com/user-attachments/assets/c648e2e1-1a18-4b2b-81bc-2da6230d05f8">

**Comment by qhfan** [comment]
* In code implementation, the denominator part still exists.
* That seems our mistake, thank you for pointing out it. Actually we use the $\kappa(Q)$ to get $\alpha$. We will fix it in the next version.

**Comment by Journey7331** [comment]
thx!
